var err;try{alert(foo)}catch(err){}alert(err)